Repository zooniverse/pfe-lab, pull requests merged in 2022-02, with the labels that each got.

#258 [Security] Update markdownz to 7.8.1
  package-lock.json
  package.json
Labels: security

#268 Refactor for zooniverse shared workflows
  .github/workflows/deploy_branch.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
Labels: ops

#271 Upgrade webpack-dev-server to v4
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies
